spring:
  datasource:
    url: jdbc:mysql://localhost/zonagamer
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  # Jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

# Server port
server:
  port: 8080